# Numpy 给数组增加一个维度

In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
arr.shape

(5,)

## 方法一

In [4]:
np.newaxis is None

True

In [5]:
np.newaxis == None

True

### 给一维向量添加一个行的维度

In [7]:
arr[np.newaxis, :]

array([[0, 1, 2, 3, 4]])

In [8]:
arr[np.newaxis, :].shape

(1, 5)

### 给一维向量添加一个列维度

In [9]:
arr[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [10]:
arr[:, np.newaxis].shape

(5, 1)

## 方法二: np.expand_dims方法

In [11]:
arr

array([0, 1, 2, 3, 4])

### 给一维向量添加一个列维度

In [12]:
np.expand_dims(arr, axis=0)

array([[0, 1, 2, 3, 4]])

In [13]:
np.expand_dims(arr, axis=0).shape

(1, 5)

### 给一维向量添加一个列维度

In [14]:
np.expand_dims(arr, axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [15]:
np.expand_dims(arr, axis=1).shape

(5, 1)

## 方法3: np.reshape

In [17]:
arr

array([0, 1, 2, 3, 4])

In [18]:
np.reshape(arr, (1,5))

array([[0, 1, 2, 3, 4]])

In [19]:
np.reshape(arr, (1, -1))

array([[0, 1, 2, 3, 4]])

In [20]:
np.reshape(arr, (1, -1)).shape

(1, 5)

In [21]:
np.reshape(arr, (-1,1))

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [22]:
np.reshape(arr, (-1,1)).shape

(5, 1)