# Numpy 对数组按索引查询

+ 基础索引
+ 神奇索引
+ 布尔索引

In [2]:
import numpy as np

In [3]:
# 一维向量
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 二维向量
X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 基础索引

### 一维数组


In [5]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
print(x[2], x[5], x[-1])

2 5 9


In [7]:
x[2:4]

array([2, 3])

In [8]:
x[2:-1]

array([2, 3, 4, 5, 6, 7, 8])

In [9]:
x[-3:]

array([7, 8, 9])

In [10]:
x[:-3]

array([0, 1, 2, 3, 4, 5, 6])

### 二维数组

In [11]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [12]:
X[0,0]

0

In [13]:
X[-1, 2]

17

In [14]:
X[2]

array([10, 11, 12, 13, 14])

In [15]:
X[-1]

array([15, 16, 17, 18, 19])

In [16]:
X[:-1]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
X[:2, 2:4]

array([[2, 3],
       [7, 8]])

In [18]:
X[:, 2]

array([ 2,  7, 12, 17])

### 注意：numpy的修改会修改原来的额数组

In [20]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
x[2:4] = 666
x

array([  0,   1, 666, 666,   4,   5,   6,   7,   8,   9])

In [23]:
X[:1,:2]

array([[0, 1]])

In [24]:
X[:1,:2] = 666
X

array([[666, 666,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])