# Numpy 对数组按索引查询

+ 基础索引
+ 神奇索引
+ 布尔索引

In [1]:
import numpy as np

In [2]:
# 一维向量
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 二维向量
X = np.arange(20).reshape(4, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

## 基础索引

### 一维数组


In [4]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
print(x[2], x[5], x[-1])

2 5 9


In [6]:
x[2:4]

array([2, 3])

In [7]:
x[2:-1]

array([2, 3, 4, 5, 6, 7, 8])

In [8]:
x[-3:]

array([7, 8, 9])

In [9]:
x[:-3]

array([0, 1, 2, 3, 4, 5, 6])

### 二维数组

In [10]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
X[0,0]

0

In [12]:
X[-1, 2]

17

In [13]:
X[2]

array([10, 11, 12, 13, 14])

In [14]:
X[-1]

array([15, 16, 17, 18, 19])

In [15]:
X[:-1]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
X[:2, 2:4]

array([[2, 3],
       [7, 8]])

In [17]:
X[:, 2]

array([ 2,  7, 12, 17])

### 注意：numpy的修改会修改原来的额数组

In [18]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x[2:4] = 666
x

array([  0,   1, 666, 666,   4,   5,   6,   7,   8,   9])

In [20]:
X[:1,:2]

array([[0, 1]])

In [21]:
X[:1,:2] = 666
X

array([[666, 666,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19]])

## 神奇索引

### 一维数组

In [23]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
indexs = np.array([[0,2],[1,3]])
x[indexs]

array([[0, 2],
       [1, 3]])

#### 实例: 获取数组中最大的前N个数字

In [26]:
arr = np.random.randint(1, 100, 10)
arr

array([85, 23, 97, 16, 72, 30, 32, 22, 12, 84])

In [27]:
arr.argsort()[-3:]

array([9, 0, 2])

In [28]:
arr[arr.argsort()[-3:]]

array([84, 85, 97])

### 二维数组

In [30]:
X = np.arange(20).reshape(4,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
X[[0,2]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [32]:
X[[0,2],:]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [33]:
X[:, [0,2,3]]

array([[ 0,  2,  3],
       [ 5,  7,  8],
       [10, 12, 13],
       [15, 17, 18]])

In [34]:
X[[0,2,3],[1,3,4]]

array([ 1, 13, 19])

## 布尔索引

### 一维数组

In [37]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
x>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [39]:
x[x>5]

array([6, 7, 8, 9])

In [40]:
x[x<=5] = 0
x[x>5] = 1
x

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [42]:
x = np.arange(10)
x[x < 5] += 20
x

array([20, 21, 22, 23, 24,  5,  6,  7,  8,  9])

### 二维数组

In [44]:
X = np.arange(20).reshape(4,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [45]:
X > 5

array([[False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [46]:
X[X > 5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [47]:
X[:, 3] > 5

array([False,  True,  True,  True])

In [48]:
X[X[:, 3] > 5]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [49]:
X[X[:, 3] > 5] = 666
X

array([[  0,   1,   2,   3,   4],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [50]:
### 组合查询

In [52]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
condition = (x % 2 == 0) | (x > 7)
condition

array([ True, False,  True, False,  True, False,  True, False,  True,
        True])

In [54]:
x[condition]

array([0, 2, 4, 6, 8, 9])