# Numpy数组合并操作

In [1]:
import numpy as np

## 1. 给数据添加信的多行

In [2]:
a = np.arange(6).reshape(2,3)

In [3]:
b = np.random.randint(10, 20, size=(4,3))

In [4]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
b

array([[17, 10, 16],
       [19, 19, 18],
       [18, 11, 16],
       [19, 12, 19]])

In [6]:
np.concatenate([a,b])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [17, 10, 16],
       [19, 19, 18],
       [18, 11, 16],
       [19, 12, 19]])

In [7]:
np.vstack([a,b])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [17, 10, 16],
       [19, 19, 18],
       [18, 11, 16],
       [19, 12, 19]])

In [8]:
np.row_stack([a,b])

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [17, 10, 16],
       [19, 19, 18],
       [18, 11, 16],
       [19, 12, 19]])

## 2. 添加多列

In [9]:
a = np.arange(12).reshape(3,4)

In [10]:
b = np.random.randint(10,20,size=(3,2))

In [11]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
b

array([[14, 17],
       [15, 16],
       [15, 14]])

In [13]:
np.concatenate([a,b], axis=1)

array([[ 0,  1,  2,  3, 14, 17],
       [ 4,  5,  6,  7, 15, 16],
       [ 8,  9, 10, 11, 15, 14]])

In [14]:
np.hstack([a,b])

array([[ 0,  1,  2,  3, 14, 17],
       [ 4,  5,  6,  7, 15, 16],
       [ 8,  9, 10, 11, 15, 14]])

In [15]:
np.column_stack([a,b])

array([[ 0,  1,  2,  3, 14, 17],
       [ 4,  5,  6,  7, 15, 16],
       [ 8,  9, 10, 11, 15, 14]])