### array本身的属性

- shape: 返回一个元组， 表示array的维度
- ndim: 一个数字，表示array的维度的数目
- size: 一个数字，表示array中所有数据元素的数目
- dtype: array中元素的数据类型

### 创建array的方法

- 从Python的列表嵌套列表创建array
- 使用预定函数 arange, ones/ones_like, zero/zero_like, empty/empty_like, full/full_like, eye
- 生成随机数的np.random模块构建


## 1. 使用Python的List和嵌套List创建一维的array和二维的array



In [2]:
import numpy as np

In [4]:
x = np.array([1,2,3,4,5,6,7,8])
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
X = np.array(
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
)
X

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## 2. 探索数组array的属性

In [6]:
x.shape

(8,)

In [7]:
X.shape

(2, 4)

In [8]:
x.ndim

1

In [9]:
X.ndim

2

In [10]:
x.size

8

In [11]:
X.size

8

In [12]:
x.dtype

dtype('int64')

In [13]:
X.dtype

dtype('int64')

## 3. 创建array便捷的函数

### 使用arange创建数字序列

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

### 使用ones创建全是1的数组

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### 使用ones_like创建形状相同的数组

In [19]:
np.ones_like(x)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
np.ones_like(X)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

### 使用zeros创建全是0的数组

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### 使用zeros_like创建形状相同的数组

In [23]:
np.zeros_like(x)

array([0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.zeros_like(X)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

### 使用empty创建全是0的数组

In [25]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.empty((2,4))

array([[-3.10503618e+231, -2.00390154e+000,  1.97626258e-323,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000, -3.10503618e+231,
         5.60609070e-309]])

### 使用empty_likes

In [30]:
np.empty_like(x)

array([-1152921504606846976, -4611677232943702691,                    4,
                          0,                    0,                    0,
       -1152921504606846976,     1134685390523447])

In [31]:
np.empty_like(X)

array([[-1152921504606846976, -4611677232943702691,                    4,
                           0],
       [                   0,                    0, -1152921504606846976,
            1134685390523447]])

### 使用full创建指定值的数组

In [32]:
np.full(10, 666)

array([666, 666, 666, 666, 666, 666, 666, 666, 666, 666])

In [33]:
np.full((2,4), 333)

array([[333, 333, 333, 333],
       [333, 333, 333, 333]])

### 使用full_like

In [36]:
np.full_like(x, 666)

array([666, 666, 666, 666, 666, 666, 666, 666])

In [37]:
np.full_like(X, 333)

array([[333, 333, 333, 333],
       [333, 333, 333, 333]])

### 使用random生成随机数的数组

In [38]:
np.random.randn()

0.45230366594566407

In [39]:
np.random.randn(3)

array([0.819339  , 1.13856417, 0.58758364])

In [40]:
np.random.randn(3,2)

array([[ 0.44461553,  0.20598359],
       [ 0.00392391,  2.78969411],
       [-0.91727573,  0.00994685]])

In [41]:
np.random.randn(3,2,4)

array([[[-0.07221852, -0.38530167, -0.98285382, -0.43852574],
        [ 1.17898066, -0.33874991,  0.63215028,  0.46236165]],

       [[-0.99687844, -0.39040603, -0.35822693,  1.50322293],
        [-0.3815182 , -0.40736824,  0.48370063,  0.46899348]],

       [[ 1.77989345,  0.0914886 , -1.22624417,  0.22330555],
        [ 0.28192739, -0.95116304, -1.43122878,  0.65834911]]])

## 4. array支持函数

In [43]:
A = np.arange(10).reshape(2, 5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
A.shape

(2, 5)

In [45]:
A + 1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [46]:
A * 3

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [47]:
np.sin(A)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [48]:
np.exp(A)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
        8.10308393e+03]])

In [49]:
B = np.random.randn(2, 5)
B

array([[-1.09470137,  1.78632937, -2.17277504, -0.16897489, -0.03210409],
       [-0.65522047, -0.70551906, -0.71135902, -0.81045341,  1.30135255]])

In [50]:
A + B

array([[-1.09470137,  2.78632937, -0.17277504,  2.83102511,  3.96789591],
       [ 4.34477953,  5.29448094,  6.28864098,  7.18954659, 10.30135255]])

In [51]:
A - B

array([[ 1.09470137, -0.78632937,  4.17277504,  3.16897489,  4.03210409],
       [ 5.65522047,  6.70551906,  7.71135902,  8.81045341,  7.69864745]])